windowrule {
  name = kitty-rules
  match:title = ^(kitty)$

  float = on
  center = on
  size = 70% 70%
}

windowrule {
  name = alacritty-rules
  match:title = ^(alacritty)$

  float = on
  center = on
  size = 70% 70%
}

windowrule {
  name = iwgtk-rules
  match:title = ^(iwgtk)$

  float = on
  center = on
  size = 70% 70%
}
