#!/bin/bash
##
#
# Take screenshot of active monitor in hyprland
#
# Requirements: hyprland, grim, notify-send, jq
#
##
# equk 2023 - equk.co.uk
#
# https://github.com/equk/dotfiles
##

# Take screenshot of current active monitor


active_workspace_monitor=$(hyprctl -j activeworkspace | jq -r '(.monitor)')
screenshot_filename="$HOME/Pictures/screenshots/$(date +"%d-%m-%Y-%H%S")-$active_workspace_monitor.png"


case $1 in 
    full)
    grim -o $active_workspace_monitor $screenshot_filename
    ;;
    selected)
    grim -g "$(slurp)" $screenshot_filename
esac


if [ -e $screenshot_filename ]; then
    notify-send -t 500 -i $screenshot_filename "Grim" "Active Monitor Screenshot Saved \n $screenshot_filename"

else
    notify-send "Couldn't take screenshot for some reason. debug it."    
fi
